spring.application.name=api-gateway
server.port = 9001
spring.main.web-application-type=reactive
spring.cloud.gateway.discovery.locator.enabled = true

## GraphQL Service Route
spring.cloud.gateway.routes[0].id=graphql-servicez
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/graphql
spring.cloud.gateway.routes[0].filters[0]=Auth

## Chat Service Route
spring.cloud.gateway.routes[1].id=chat-service
spring.cloud.gateway.routes[1].uri=http://localhost:9090
spring.cloud.gateway.routes[1].predicates[0]=Path=/api
spring.cloud.gateway.routes[1].filters[0]=Auth

## Notifications Service Route
spring.cloud.gateway.routes[2].id=notifications-service
spring.cloud.gateway.routes[2].uri=http://localhost:6007
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/notifications
spring.cloud.gateway.routes[2].filters[0]=Auth

## Auth Service Route
spring.cloud.gateway.routes[3].id=auth-service
spring.cloud.gateway.routes[3].uri=http://localhost:7007
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/auth/**

## Socket Service Route
spring.cloud.gateway.routes[4].id=socket-service
spring.cloud.gateway.routes[4].uri=ws://localhost:8900
spring.cloud.gateway.routes[4].predicates[0]=Path=/

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true
